name: Slither Analysis

on:
  pull_request:
    branches: [ main ]
jobs:
  analyze:
    runs-on: ubuntu-latest
    env:
      API_URL: ${{ secrets.POPP_ERC20_API_URL }}
    steps:
      - uses: actions/checkout@v3
      - name: Copy .env
        run: cp .env.example .env
      - name: Run Slither
        uses: crytic/slither-action@v0.2.0
        id: slither
        with:
          sarif: results.sarif
          fail-on: all

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.slither.outputs.sarif }}
